### PR TITLE
Ecma datamodel

### LINKED ISSUE #175: error test/scxml-test-framework/test/w3c-ecma/test558.txml.scxml
[https://github.com/jbeard4/scxml-test-framework/tree/master/test/scxml-test-framework/test/w3c-ecma/test558.txml.scxml](https://github.com/jbeard4/scxml-test-framework/tree/master/test/scxml-test-framework/test/w3c-ecma/test558.txml.scxml)

**Error** <code><pre>null</code></pre>
**Data**: <code><pre>"Unexpected identifier"</code></pre>
**scxml**: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- in the ECMA data model, test that if the child of <data> is not XML, or if XML is loaded via src=, 
 the processor treats the value as a string, does whitespace normalization and assigns it to the var.-->
<scxml xmlns="http://www.w3.org/2005/07/scxml" xmlns:conf="http://www.w3.org/2005/scxml-conformance" initial="s0" version="1.0" datamodel="ecmascript">
 <datamodel>
   <data id="var1">
this  is 
a string 
</data>
  <data id="var2" src="file:test558.txt"/> 
  </datamodel>
  
<state id="s0">
   <transition cond="var1 == 'this is a string'" target="s1"/>
   <transition target="fail"/>
  </state>
  
<state id="s1">
   <transition cond="var2 == 'this is a string'" target="pass"/>
   <transition target="fail"/>
   </state>
    
<final id="pass"><onentry><log label="Outcome" expr="'pass'"/></onentry></final>
<final id="fail"><onentry><log label="Outcome" expr="'fail'"/></onentry></final>  

</scxml>
```
**JSON**:  <code><pre>{
  "initialConfiguration": [
    "pass"
  ],
  "events": []
}</code></pre>

### LINKED ISSUE #178: fail test/scxml-test-framework/test/w3c-ecma/test552.txml.scxml
[https://github.com/jbeard4/scxml-test-framework/tree/master/test/scxml-test-framework/test/w3c-ecma/test552.txml.scxml](https://github.com/jbeard4/scxml-test-framework/tree/master/test/scxml-test-framework/test/w3c-ecma/test552.txml.scxml)

**Error** <code><pre>{
  "name": "AssertionError",
  "actual": [
    "fail"
  ],
  "expected": [
    "pass"
  ],
  "operator": "deepEqual",
  "message": "[\"fail\"] deepEqual [\"pass\"]"
}</code></pre>
**Data**: <code><pre>{
  "sessionToken": 435,
  "nextConfiguration": [
    "fail"
  ]
}</code></pre>
**scxml**: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- test that src content can be used to assign a value to a var. Edit
test552.txt to have a value that's legal for the datamodel in question -->
<scxml xmlns="http://www.w3.org/2005/07/scxml" xmlns:conf="http://www.w3.org/2005/scxml-conformance" initial="s0" version="1.0" datamodel="ecmascript">
  <datamodel>
    <data id="Var1" src="file:test552.txt"/>
    </datamodel>
    
   <state id="s0">
 
       <transition cond="Var1" target="pass"/>
       <transition target="fail"/>
   </state>

   <final id="pass"><onentry><log label="Outcome" expr="'pass'"/></onentry></final>
   <final id="fail"><onentry><log label="Outcome" expr="'fail'"/></onentry></final>
   


</scxml>
```
**JSON**:  <code><pre>{
  "initialConfiguration": [
    "pass"
  ],
  "events": []
}</code></pre>

### LINKED ISSUE #307: Support data/@src
Load up file contents into data attribute.

### PR DESCRIPTION
**Pull request by feyzo**
Final state of the test module javascript:
https://gist.github.com/feyzo/b25e9d0730477d2fbe15

Got the idea from here:
http://www.w3.org/TR/xmlschema-1/#d0e1654

What do you think?

Closes #175 
Closes #178
Closes #307 

Closing 1 erroring 1 failing tests.
Passing total of 164 tests, 61 of those from w3c.
Leaving 11 erroring and 92 failing tests.

### CODE REVIEW

File: lib/compiler/static-analysis/scjson-analyzer.js [hunk 1]
```diff
@@ -69,8 +69,39 @@ var scJsonAnalyzer = {
...
+					asyncStarted();
+
+					getFileContents(node.src.substring(5), function (error, content) {
+						if(error) {
+							done([error]);
+						} else {
+							delete node.src;
+							node.expr = { 	$column: node.$column,
+											$line: node.$line,
+											expr: "\"" + normalizeWhitespace(content.toString()) + "\""
```
Comment (jbeard4) [inline lib/compiler/static-analysis/scjson-analyzer.js]: If the string contains a double quote this will totally break. You should just JSON.stringify on content.toString() to escape it.

File: lib/compiler/static-analysis/scjson-analyzer.js [hunk 2]
```diff
@@ -69,8 +69,39 @@ var scJsonAnalyzer = {
...
+										};
+
+							done(null, node);
+						}
+					});
+				} else if(node.content) {
+					var errors = validateJavascriptAssignment(node.id, node.content);
+
+					if(errors.length > 0) {
+						node.content.expr = "\"" + normalizeWhitespace(node.content.expr.toString()) + "\"";
```
Comment (jbeard4) [inline lib/compiler/static-analysis/scjson-analyzer.js]: Same here
